In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import polars as pl
import seaborn as sns

import constants
import experiments
import data_loader
import plots

In [2]:
k_nns = (1, 3, 5)

In [4]:
dfs = []
for k in k_nns:
    for model in constants.MODELS:
        for party in constants.PARTIES:
            embeddings = data_loader.load_sotu_data(party, model)
            df = experiments.mean_experiment(k, party,model, embeddings)
            dfs.append(df)
data = pd.concat(dfs)
data.to_parquet("timeness.parquet", index=False)

In [5]:
data

,Timeness,Experiment,Date,k-NN,Model,Party
0,-0.054496,1-Republican-ada-002,1988-01-25,1,ada-002,Republican
1,-0.017198,1-Republican-ada-002,1990-01-31,1,ada-002,Republican
2,-0.000359,1-Republican-ada-002,1991-01-29,1,ada-002,Republican
3,-0.009563,1-Republican-ada-002,1992-01-28,1,ada-002,Republican
4,0.005150,1-Republican-ada-002,2002-01-29,1,ada-002,Republican
...,...,...,...,...,...,...
22,0.007763,5-All-voyage-lite-01,2014-01-28,5,voyage-lite-01,All
23,0.010908,5-All-voyage-lite-01,2015-01-20,5,voyage-lite-01,All
24,0.006257,5-All-voyage-lite-01,2016-01-12,5,voyage-lite-01,All
25,0.009692,5-All-voyage-lite-01,2018-01-30,5,voyage-lite-01,All
26,0.019264,5-All-voyage-lite-01,2019-02-05,5,voyage-lite-01,All

In [ ]:
sns.lineplot(data=data, x=constants.DATE_COL, y=constants.DIMENSION_COL, hue=constants.EXPERIMENT_COL, style=constants.K_COL)

In [ ]:
def plot_correlation(dataset, x="Date", y="Timeness"):
    dataset.plot(x=x, y=y, marker="o", linestyle="-", color="b")
    correlation = dataset[y].corr(dataset[x], method="kendall")
    print(f"Correlation: {correlation:.2f}")

In [ ]:
plot_correlation(ada_timeness)
plot_correlation(voyage_timeness)

In [ ]:
ada_timeness